apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-java-app
  labels:
    app: gcp-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-java-app
  template:
    metadata:
      labels:
        app: gcp-java-app
    spec:
      containers:
      - name: gcp-java-app
        image: ganesh077/sprigboot-cicd:10
        ports:
        - containerPort: 8080
